name: Terraform Infra Workflow
run-name: Run message by @${{ github.actor }}
on: workflow_dispatch
env:
  name: 'sunil kumar'
jobs:
  my_first_job:
    name: Deploy To Test Env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Greeting
        run: |
          echo "Hello World!! Good Night"
          echo "This workflow run by $name"
      - name: Print Message
        run: echo "Hello from Guthub Hosted Agent"
  my_second_job:
    name: Deploy To Dev Env
    runs-on: ubuntu-latest
    needs: my_first_job
    continue-on-error: true
    steps:
      - name: Print Message
        run: echo "Hello Ubuntu-latest"
  my_third_job:
    name: Deploy To Prod Env
    runs-on: windows-latest
    needs: my_second_job
    continue-on-error: true
    env:
      COUNTRY: 'INDIA'
      MESSAGE: 'GOOD MORNING'
    steps:
      - name: Print Message
        run: | 
          write-host "Hello Window-Latest $env:COUNTRY"
          write-host "$env:MESSAGE from Window Runner"
    
      


